config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  devise_for :users, controllers: { registrations: 'registrations',
                                    omniauth_callbacks: 'users/omniauth_callbacks' }
  root 'questions#index'

  resources :users do
    member do
      get :questions
      patch :change_role
    end
  end

  concern :votable do
    member do
      post :vote
    end
  end

  resources :questions, concerns: [:votable] do
    resources :comments, concerns: [:votable] do
      member do
        post :best
      end
    end
  end

  resources :tags, only: %i[show index]

  resource :search, only: %i[new show edit]

  get '/auth/:provider/callback', to: 'registrations#create'

  mount ActionCable.server => '/cable'

  namespace :api do
    namespace :v1 do
      resource :profiles do
        get :me, on: :collection
      end
      resources :questions
    end
  end
end

app/models/question.rb
class Question < ActiveRecord::Base
  include Votable
  include Votes_Calculator
  has_many :comments, dependent: :destroy
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings, dependent: :destroy
  belongs_to :user
  validates :title, :body, presence: true
  is_impressionable

  def self.search(search)
    if search.present?
      Question.where('title LIKE ? OR body LIKE ?',
                     "%#{search}%", "%#{search}%")
    else
      Question.all
    end
  end

  def all_tags
    self.tags.map(&:name).join(', ')
  end

  def all_tags=(names)
    names = names.split(',').map(&:strip).select { |t| t.size > 1 }
    self.tags = names.map do |name|
      Tag.where(name: name.strip).first_or_create!
    end
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController  < Api::V1::BaseController
  def index     
    @questions = Question.all
    respond_with @questions
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :find_question, only: %i[show edit update destroy vote]
  impressionist actions: [:show], unique: [:session_hash]
  authorize_resource
  include Voted

  respond_to :html, except: %i[update vote unvote]
  respond_to :js, only: %i[update]
  respond_to :json, only: %i[vote unvote]
  def index
    @questions = Question.search(params[:search])
                         .includes(:tags, :user)
                         .paginate(page: params[:page], per_page: 5)
    @tags = Tag.first(10).map(&:name)
    # Tagging.group(:tag_id).count
  end

  def show
    @comments = @question.comments.includes(:user).sort_by(&:total_votes).reverse!
    @question.impressionist_count(filter: :session_hash)
  end

  def new
    respond_with @question = Question.new
  end

  def create
    @question = current_user.questions.new(question_params)
    flash[:notice] = 'Question successfully created' if @question.save
    respond_with @question
  end

  def edit; end

  def update
    if @question.update_attributes(question_params)
      redirect_to @question
    else
      render :edit
    end
  end

  def destroy
    respond_with @question.destroy
  end

  private

  def find_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body, :all_tags)
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def tag_cloud(tags)

  end

  def question_link_class(question)
    current_page?(question_path(question)) ? "" : "link "
  end
end

app/views/questions/_form.html.erb
<%= form_for @question, :html => {:class => 'ui form'} do |f| %>
    <%= render 'common/errors', resource: @question  %>
  <div class="field">
    <%= f.label :Title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :Question %>
    <%= f.text_area :body %>
  </div>

    <div class="field">
      <%= f.label :Tags %>
      <%= f.text_field :all_tags %>
    </div>

    <%= f.submit 'Post Your Question', class:'ui button' %>
<% end %>

app/views/questions/_question.html.erb
    <div class="ui fluid <%= question_link_class(question) %>card question">
      <div class="content">
        <div class="right floated meta">
          
            <%= question.created_at.strftime('%d %B, %Y at %H:%M:%S') %>
          
          <% if can? :update, question %>
              <%= link_to 'edit', edit_question_path(question) %>
              <%= link_to 'delete', question_path(question), method: :delete%>
          <% end %>
        </div>
        <div class="header">
          <%= link_to question.title, question_path(question) %>
        </div>
        <% if current_page?(question_path(question)) %>
            <div class="description">
              <p>
                <%= question.body %>
              </p>           
            </div>
            <div class="floated rigth">
               <div class="ui segment basic voting ">
                <% if can? :vote, question %>
                    <%= button_to vote_question_path(question, vote: true), form_class:'vote like', remote: true, method: 'post' do %>
                        <i class="angle up icon"></i>
                    <% end %>
                    <span class="<%= total_votes_color(question.total_votes) %>">
                      <%= question.total_votes %>
                    </span>
                    <%= button_to  vote_question_path(question, vote: false), form_class:'vote dislike', remote: true, method: 'post' do %>
                        <i class="angle down icon"></i>
                    <% end %>
                  <% else %>
                    <span class="<%= total_votes_color(question.total_votes) %>">
                      <%= pluralize(question.total_votes, 'vote') %> 
                    </span>
                <% end %>
                <div>        
                <%= pluralize(question.impressionist_count, 'view') %>
                </div>
                <div id="number_comments">
                <%= pluralize(question.comments.published.count, 'comment') %>
                </div>
            </div>
            </div>
         
        <% end %>
      </div>
      <div class="extra content">
        <div class="item">
          <span class="left floated ">
            <%= raw question.tags.map(&:name).map{|t| link_to t, tag_path(t), class: 'ui label' }.join(' ') %>
          </span>
          <div class="right floated author">
            <%= link_to  user_path(question.user), class:'ui image label' do %>
                <%= avatar_for(question.user) %>
                <%= question.user.login %>
            <% end %>
          </div>
        </div>
      </div>
    </div>

app/views/questions/edit.html.erb
<%= render 'form' %>

app/views/questions/index.html.erb
<div class="ui stackable mobile vertically reversed grid">
  <div class="twelve wide column">
    <%= form_tag questions_path, method: 'get' do %>
        <div class="ui action fluid input">
          <%= text_field_tag :search, params[:search], placeholder: 'Enter question...' %>
          <%= button_tag 'Search Question', name: nil, class: 'ui button'  %>
        </div>
    <% end %>
    <h1>Questions
      <%= link_to  new_question_path, class: 'ui right floated small teal labeled icon button' do %>
          <i class="add icon"></i> Ask Question
      <% end %>
    </h1>
    <% if @questions.any? %>
        <%= render @questions %>
    <% else %>
      <h4>No questions</h4>
    <% end %>
    <%= will_paginate @questions %>
  </div>
  <div class="four wide  column">
    <div class="ui labels">
      <h3 class="ui dividing header">Tags</h3>
      <% @tags.each do |t| %>
          <%=  link_to t, tag_path(t), class: 'ui label' %>
      <% end %>
    </div>
  </div>
</div>

app/views/questions/new.html.erb
<h2 class="ui dividing header">
  Create new question
</h2>
<%= render 'form' %>

app/views/questions/show.html.erb
  <%= render @question %>
<h3 class="ui dividing header">Comments</h3>
<div class="ui comments">
  <%= render @comments %>
</div>
<% if can? :create, Comment %>
    <%= render 'comments/form' %>
<% else%>
    <div class="ui message">
      <div class="header">
        Info
      </div>
      <p>You need to sign in or sign up before post your comment.</p>
      <p>
        <%= link_to('Login', new_user_session_path)  %>
        or
        <%= link_to('Sign up', new_user_registration_path)  %>
      </p>
    </div>
<% end %>