config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  devise_for :users, controllers: { registrations: 'registrations',
                                    omniauth_callbacks: 'users/omniauth_callbacks' }
  root 'questions#index'

  resources :users do
    member do
      get :questions
      patch :change_role
    end
  end

  concern :votable do
    member do
      post :vote
    end
  end

  resources :questions, concerns: [:votable] do
    resources :comments, concerns: [:votable] do
      member do
        post :best
      end
    end
  end

  resources :tags, only: %i[show index]

  resource :search, only: %i[new show edit]

  get '/auth/:provider/callback', to: 'registrations#create'

  mount ActionCable.server => '/cable'

  namespace :api do
    namespace :v1 do
      resource :profiles do
        get :me, on: :collection
      end
      resources :questions
    end
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  include Archivable
  include Votable
  include Votes_Calculator
  belongs_to :question
  belongs_to :user
  validates :content, presence: true
  default_scope { where(deleted: false) }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, except: %i[new index]
  before_action :find_question
  before_action :find_comment, only: %i[edit update destroy best]
  authorize_resource
  include Voted

  respond_to :js, except: %i[vote unvote best]
  respond_to :json, only: %i[vote unvote best]
  def new
    respond_with(@comment = Comment.new)
  end

  def create
    @comment = @question.comments.build(comment_params.merge(user_id: current_user.id))
    respond_to do |format|
      if @comment.save
        format.js
      else
        format.js { render status: 400 }
      end
    end
  end

  def edit; end

  def update
    respond_to do |format|
      format.js if @comment.update(comment_params)
    end
  end

  def destroy
    @comment.destroy
    respond_to do |format|
      format.js
    end
  end

  def best
    @question.comments.update_all best: false
    @comment.update_attribute :best, params[:best]
    respond_to do |format|
      format.json { render json: @comment }
    end
  end

  private

  def find_question
    @question = Question.find(params[:question_id])
  end

  def find_comment
    @comment = @question.comments.published.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:content, :best)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
    def best_comment_icon_class(best)
        best ? 'green' :  ''        
    end
end

app/views/comments/_comment.html.erb
<div class="comment" id="comment_id_<%= comment.id %>">
  <div class="avatar">
    <%= avatar_for(comment.user) %>
  </div>
  <div class="content">
    <div class="header">

      <%= link_to comment.user.login, user_path(comment.user), class: 'author' %>
      <div class="metadata">
        <span class="date"> <%= comment.created_at.strftime('%d %B, %Y at %H:%M:%S') %></span>
      </div>
      <div class="floated rigth">
        <div class="voting">
          <% if can? :vote, comment %>
            <%= button_to   vote_question_comment_path(comment.question, comment, vote: true), form_class: 'vote like', remote: true, method: 'post' do %>
                <i class="angle up icon"></i>
            <% end %>
            <span class="<%= total_votes_color(comment.total_votes) %>"><%= comment.total_votes %></span>
            <%= button_to   vote_question_comment_path(comment.question, comment, vote: false), form_class: 'vote dislike', remote: true, method: 'post' do %>
                <i class="angle down icon"></i>
            <% end %>
          <% end %>
        </div>
        <div class="make-best">
          <% if can? :best, comment %>                      
            <%= button_to  best_question_comment_path(comment.question, comment, best: true), disabled: comment[:best], title: 'make best',  class: 'ui icon button', remote: true, method: 'post' do  %>
              <i class="check icon large <%= best_comment_icon_class(comment[:best]) %>"></i>
            <% end %>                     
          <% elsif comment[:best] == true %>
            <i class="check icon large green" title="The question owner accepted this as the best answer"></i>
          <% end %>
        </div>
    </div>
    <div class="text">
      <%= comment.content %>
    </div>
    <div class="actions">
      <% if can? :update, comment %>
          <%= link_to "Edit", '', class: 'edit-comment-link', data: { comment_id: comment.id } %>
          <%= link_to "Delete", [comment.question, comment],
                     method: :delete, remote: true, data:{ confirm: "Are u sure?"} %>
      <% end %>
    </div>
    <br>
    <%= form_for([@question, comment], remote: true,
                 html: { class: 'ui form hidden', id:"edit_comment_form_#{ comment.id }" }) do |f|%>
        <div class="field">
          <%= f.label "Comment"%>
          <%= f.text_area :content%>
        </div>
        <%= f.submit 'Edit', class:'ui blue submit button' %>
    <% end %>
  </div>
</div>
</div>

app/views/comments/_form.html.erb
<div class="ui error message hidden comment-create">
  <div class="header">Error</div>
  <i class="close icon"></i>
  <p></p>
</div>
<%= form_for([@question, @question.comments.build], html: {class:'ui form create-form'}, remote: true) do |f| %>
    <div class="field">
      <%= f.label 'Your comment' %>
      <%= f.text_area :content %>
    </div>
    <%= f.submit 'Add comment', class:'ui blue  submit  button' %>
<% end %>

app/views/comments/create.js.erb
$message = $('.error.message.comment-create')
<% if @comment.errors.present? %>
  <% @comment.errors.full_messages.each do |m| %>
    $message.find('p').text('<%= j m.html_safe %>')
    if ( $message.hasClass('hidden') )
        $('.error.message').transition('scale');
  <% end %>
<% else %>
  if ( !$message.hasClass('hidden') )
      $('.error.message').transition('scale');
  $('.ui.comments').prepend("<%= j render @comment %>");
  $('.create-form #comment_content').val('')
<% end %>

app/views/comments/destroy.js.erb
var commentsNumber = function (){
   var number = parseInt($('#number_comments').text()) - 1;
   var text = number + ' comment'
    if (number > 1) {
        text += 's'
    }
    return text
}

$("#comment_id_<%=@comment.id%>").remove();
$("#number_comments").text(commentsNumber());

app/views/comments/edit.html.erb
<%= form_for([@question, @comment], html: {class: 'ui form'}) do |f|%>
    <div class="field">
      <%= f.label "Comment"%>
      <%= f.text_area :content%>
    </div>
  <%= f.submit 'Save', class:'ui blue submit button' %>
<% end %>

app/views/comments/new.html.erb
<%= render 'form' %>

app/views/comments/update.js.erb
<% if @comment.errors.present? %>
  <% @comment.errors.full_messages.each do |m| %>
    $('.error.message p').text('<%= j m.html_safe %>')
  <% end %>
<% else %>
  $("#comment_id_<%=@comment.id%>").html("<%= j render @comment %>");
<% end %>