config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  devise_for :users, controllers: { registrations: 'registrations',
                                    omniauth_callbacks: 'users/omniauth_callbacks' }
  root 'questions#index'

  resources :users do
    member do
      get :questions
      patch :change_role
    end
  end

  concern :votable do
    member do
      post :vote
    end
  end

  resources :questions, concerns: [:votable] do
    resources :comments, concerns: [:votable] do
      member do
        post :best
      end
    end
  end

  resources :tags, only: %i[show index]

  resource :search, only: %i[new show edit]

  get '/auth/:provider/callback', to: 'registrations#create'

  mount ActionCable.server => '/cable'

  namespace :api do
    namespace :v1 do
      resource :profiles do
        get :me, on: :collection
      end
      resources :questions
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ? auth_abilities(user) : guest_abilities
  end

  def auth_abilities(user)
    if user.admin?
      can :manage, :all
    elsif user.moderator?
      moderator_abilities(user)
    else
      user_abilities(user)
    end
  end

  def guest_abilities
    can :read, :all
    can :questions, User
    cannot :index, User
  end

  def user_abilities(user)
    guest_abilities
    can :vote, Question do |votable|
      votable.user != user
    end
    can :vote, Comment do |votable|
      votable.user != user
    end
    can :best, Comment do |comment|
      comment.question.user == user
    end
    can %i[create edit update destroy],
        [Question, Comment, User], user: user
  end

  def moderator_abilities(user)
    user_abilities(user)
    can %i[edit update destroy], [Question, Comment]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authorization.rb
class Authorization < ApplicationRecord
  belongs_to :user
end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :user
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  include Archivable
  include Votable
  include Votes_Calculator
  belongs_to :question
  belongs_to :user
  validates :content, presence: true
  default_scope { where(deleted: false) }
end

app/models/question.rb
class Question < ActiveRecord::Base
  include Votable
  include Votes_Calculator
  has_many :comments, dependent: :destroy
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings, dependent: :destroy
  belongs_to :user
  validates :title, :body, presence: true
  is_impressionable

  def self.search(search)
    if search.present?
      Question.where('title LIKE ? OR body LIKE ?',
                     "%#{search}%", "%#{search}%")
    else
      Question.all
    end
  end

  def all_tags
    self.tags.map(&:name).join(', ')
  end

  def all_tags=(names)
    names = names.split(',').map(&:strip).select { |t| t.size > 1 }
    self.tags = names.map do |name|
      Tag.where(name: name.strip).first_or_create!
    end
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings, dependent: :destroy
  has_many :questions, through: :taggings, dependent: :destroy

  def self.counts
    # self.select("name, count(taggings.tag_id) as count").joins(:taggings).group("taggings.tag_id")
  end

end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :question
  belongs_to :tag
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :recoverable,
         :confirmable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: %i[facebook]
  mount_uploader :avatar, AvatarUploader
  has_many :comments, dependent: :destroy
  has_many :questions, dependent: :destroy
  has_many :authorizations, dependent: :destroy
  has_many :votes
  enum role: { user: 0, admin: 1, moderator: 2 }

  validates :login, :country, :country, :city, :address, presence: true

  def change_role(user, role)
    user.update(role: role) if user
  end

  def self.from_omniauth(auth)
    authorization = Authorization.where(provider: auth.provider, uid: auth.uid.to_s).first
    return authorization.user if authorization
    email = auth[:info][:email]
    user = User.where(email: email).first
    if user
      user.create_auth(auth)
    else
      login = email.split('@').first
      password = Devise.friendly_token[0, 10]
      oauth_avatar_url = auth.info.image ? auth.info.image.gsub('http://', 'https://') : ''
      user = User.new(email: email, login: login, password: password,
                      password_confirmation: password,  oauth_avatar_url: oauth_avatar_url,
                      country: 'uk', city: 'kh', address: 'sh')
      user.skip_confirmation!
      user.save
      user.create_auth(auth)
    end
    user
  end

  def create_auth(auth)
    self.authorizations.create(provider: auth.provider, uid: auth.uid.to_s)
  end
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :votable, polymorphic: true
  validates :user_id, uniqueness: { scope: [:votable_type, :votable_id] }
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @book = Book.all
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @user.save
      flash[:succses] = 'Book created'
      redirect_to @book
    else
      render 'new'
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    @book.update!(book_params)
    flash[:notice] = 'Книга обновлена'
    redirect_to @book
  end

  private

  def book_params
    params.require(:book).permit(:author, :description, :user_id)
  end
end

app/controllers/tagging_controller.rb
class TaggingController < ApplicationController
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index; end
  def show
    @tag = Tag.find_by(name: params[:id])
    @questions = @tag.questions.includes(:user, :tags)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])
    sign_in_and_redirect @user, event: :authentication
    set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  authorize_resource
  before_action :find_user, only: %i[show edit update questions change_role]
  def index
    @users = User.all.paginate(page: params[:page], per_page: 15)
  end

  def questions
    @questions = @user.questions.includes(:tags)
  end

  def show; end

  def edit; end

  def update
    if @user.update(user_params)
       flash[:notice] = 'Your account has been updated'
       redirect_to @user
     else
       render :show
     end
  end

  def change_role
    if @user.update_attribute(:role, params[:role])
      flash[:notice] = 'Role changed'
      redirect_to @user
    else
      render :show
    end
  end

  private

  def find_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:login, :email, :country, :city,
                                 :address, :avatar, :role)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
    def best_comment_icon_class(best)
        best ? 'green' :  ''        
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def tag_cloud(tags)

  end

  def question_link_class(question)
    current_page?(question_path(question)) ? "" : "link "
  end
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/tagging_helper.rb
module TaggingHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def avatar_for(user)

    if user.avatar.url
      image_tag user.avatar.url(:thumb)
    elsif user.oauth_avatar_url
      image_tag user.oauth_avatar_url
    else
      gravatar_id = Digest::MD5::hexdigest(user.email.to_s)
      gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?d=retro&amp;f=y"
      image_tag(gravatar_url, alt: user.email, class: "gravatar")
    end
  end
end

app/helpers/voted_helper.rb
module VotedHelper
  def total_votes_color(value)
    value < 0 ? 'voting-counter_negative' : 'voting-counter_positive'
  end
end

app/views/users/_change_role.html.erb
<% if can? :change_role, User %>
    <%= form_tag change_role_user_path(user), class: 'ui form', method: :patch do %>
        <%= label_tag 'Change role' %>
        <div class="two fields">
          <div class="field">
            <%= select_tag(:role, options_for_select(User.roles.keys, selected: user.role), class: 'ui dropdown' ) %>
          </div>
          <div class="field">
            <%= submit_tag("apply", class: 'ui button positive') %>
          </div>
        </div>
    <% end %>
<% end %>

app/views/users/edit.html.erb
<div class="ui two column centered grid">
    <div class="column">
        <h2 class="ui dividing header">Edit profile</h2>
<%= form_for @user, :html => {:class => 'ui form'} do |f|%>
  <div class="field">
      <%= f.label :email %>
      <%= f.text_field :email %>
      <%= @user.errors[:email].try(:first) %>
  </div>

  <div class="field">
    <%= f.label :city %>
    <%= f.text_field :city %>
    <%= @user.errors[:city].try(:first) %>
  </div>
  <div class="field">
    <%= f.label :country %>
    <%= f.text_field :country %>
    <%= @user.errors[:country].try(:first) %>
  </div>
  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
    <%= @user.errors[:address].try(:first) %>
  </div>

    <%= f.submit 'Save', {class: 'ui button'} %>
<% end %>
    </div>
  </div>

app/views/users/index.html.erb
<table  class="ui celled padded table" >
  <thead>
  <tr>
    <th>email</th>
    <th>role</th>
    <th>login</th>
    <th>country/city/address</th>
    <th>change role</th>
  </tr>
  </thead>
  <tbody>
  <% @users.each do |u|%>
      <tr>
        <td><%= link_to u.email, user_path(u)%></td>
        <td><%= u.role %></td>
        <td><%= u.login %></td>
        <td><%= u.country %>
          <%= u.city %>
          <%= u.address%>
        </td>
        <td>
          <%= render partial: 'users/change_role', locals: { user: u }  %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

<%= will_paginate @user %>

app/views/users/questions.html.erb
 <h1 class="ui dividing header"><%= @user.login %> questions</h1>
<% if @questions.any? %>
    <%= render @questions %>
<% else %>
    <h3>No questions</h3>
<% end %>

app/views/users/show.html.erb
<div class="ui card">
  <div class="image">
    <%= avatar_for(@user) %>
  </div>
  <div class="content">
    <div class="header"><%= @user.login %>
      <% if can? :change_role, User %>
          (<%= @user.role %>)
      <% end %>
    </div>
    <div class="meta">
      <span class="date"><%= @user.created_at.strftime('%d %B, %Y at %H:%M:%S') %></span>
    </div>
    <div class="description">
      <p><%= @user.email %></p>
      <p><%= @user.country %> <%= @user.city %> <%= @user.address %></p>
    </div>
  </div>
  <div class="extra content">
    <%= link_to questions_user_path(@user) do %>
      <i class="help icon"></i>
      <%= @user.questions.count %> 
    <% end %>
    <i class="comments icon"> </i>
    <%= @user.comments.count %>
    <div class="right floated ">
      <% if @user == current_user %>
          <div>
            <%= link_to 'Change Password or Email',  edit_user_registration_path %>
          </div>
          <div>
            <%= link_to 'Edit profile', edit_user_path(@user) %>
          </div>
      <% end %>
    </div>
  </div>
</div>

<%= render partial: 'users/change_role', locals: { user: @user }  %>