config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  devise_for :users, controllers: { registrations: 'registrations',
                                    omniauth_callbacks: 'users/omniauth_callbacks' }
  root 'questions#index'

  resources :users do
    member do
      get :questions
      patch :change_role
    end
  end

  concern :votable do
    member do
      post :vote
    end
  end

  resources :questions, concerns: [:votable] do
    resources :comments, concerns: [:votable] do
      member do
        post :best
      end
    end
  end

  resources :tags, only: %i[show index]

  resource :search, only: %i[new show edit]

  get '/auth/:provider/callback', to: 'registrations#create'

  mount ActionCable.server => '/cable'

  namespace :api do
    namespace :v1 do
      resource :profiles do
        get :me, on: :collection
      end
      resources :questions
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ? auth_abilities(user) : guest_abilities
  end

  def auth_abilities(user)
    if user.admin?
      can :manage, :all
    elsif user.moderator?
      moderator_abilities(user)
    else
      user_abilities(user)
    end
  end

  def guest_abilities
    can :read, :all
    can :questions, User
    cannot :index, User
  end

  def user_abilities(user)
    guest_abilities
    can :vote, Question do |votable|
      votable.user != user
    end
    can :vote, Comment do |votable|
      votable.user != user
    end
    can :best, Comment do |comment|
      comment.question.user == user
    end
    can %i[create edit update destroy],
        [Question, Comment, User], user: user
  end

  def moderator_abilities(user)
    user_abilities(user)
    can %i[edit update destroy], [Question, Comment]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authorization.rb
class Authorization < ApplicationRecord
  belongs_to :user
end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :user
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  include Archivable
  include Votable
  include Votes_Calculator
  belongs_to :question
  belongs_to :user
  validates :content, presence: true
  default_scope { where(deleted: false) }
end

app/models/question.rb
class Question < ActiveRecord::Base
  include Votable
  include Votes_Calculator
  has_many :comments, dependent: :destroy
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings, dependent: :destroy
  belongs_to :user
  validates :title, :body, presence: true
  is_impressionable

  def self.search(search)
    if search.present?
      Question.where('title LIKE ? OR body LIKE ?',
                     "%#{search}%", "%#{search}%")
    else
      Question.all
    end
  end

  def all_tags
    self.tags.map(&:name).join(', ')
  end

  def all_tags=(names)
    names = names.split(',').map(&:strip).select { |t| t.size > 1 }
    self.tags = names.map do |name|
      Tag.where(name: name.strip).first_or_create!
    end
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings, dependent: :destroy
  has_many :questions, through: :taggings, dependent: :destroy

  def self.counts
    # self.select("name, count(taggings.tag_id) as count").joins(:taggings).group("taggings.tag_id")
  end

end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :question
  belongs_to :tag
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :recoverable,
         :confirmable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: %i[facebook]
  mount_uploader :avatar, AvatarUploader
  has_many :comments, dependent: :destroy
  has_many :questions, dependent: :destroy
  has_many :authorizations, dependent: :destroy
  has_many :votes
  enum role: { user: 0, admin: 1, moderator: 2 }

  validates :login, :country, :country, :city, :address, presence: true

  def change_role(user, role)
    user.update(role: role) if user
  end

  def self.from_omniauth(auth)
    authorization = Authorization.where(provider: auth.provider, uid: auth.uid.to_s).first
    return authorization.user if authorization
    email = auth[:info][:email]
    user = User.where(email: email).first
    if user
      user.create_auth(auth)
    else
      login = email.split('@').first
      password = Devise.friendly_token[0, 10]
      oauth_avatar_url = auth.info.image ? auth.info.image.gsub('http://', 'https://') : ''
      user = User.new(email: email, login: login, password: password,
                      password_confirmation: password,  oauth_avatar_url: oauth_avatar_url,
                      country: 'uk', city: 'kh', address: 'sh')
      user.skip_confirmation!
      user.save
      user.create_auth(auth)
    end
    user
  end

  def create_auth(auth)
    self.authorizations.create(provider: auth.provider, uid: auth.uid.to_s)
  end
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :votable, polymorphic: true
  validates :user_id, uniqueness: { scope: [:votable_type, :votable_id] }
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @book = Book.all
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @user.save
      flash[:succses] = 'Book created'
      redirect_to @book
    else
      render 'new'
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    @book.update!(book_params)
    flash[:notice] = 'Книга обновлена'
    redirect_to @book
  end

  private

  def book_params
    params.require(:book).permit(:author, :description, :user_id)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index; end
  def show
    @tag = Tag.find_by(name: params[:id])
    @questions = @tag.questions.includes(:user, :tags)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
    def best_comment_icon_class(best)
        best ? 'green' :  ''        
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def tag_cloud(tags)

  end

  def question_link_class(question)
    current_page?(question_path(question)) ? "" : "link "
  end
end

app/helpers/tagging_helper.rb
module TaggingHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def avatar_for(user)

    if user.avatar.url
      image_tag user.avatar.url(:thumb)
    elsif user.oauth_avatar_url
      image_tag user.oauth_avatar_url
    else
      gravatar_id = Digest::MD5::hexdigest(user.email.to_s)
      gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?d=retro&amp;f=y"
      image_tag(gravatar_url, alt: user.email, class: "gravatar")
    end
  end
end

app/helpers/voted_helper.rb
module VotedHelper
  def total_votes_color(value)
    value < 0 ? 'voting-counter_negative' : 'voting-counter_positive'
  end
end

app/views/common/_errors.html.erb
<% if resource.errors.any? %>
    <div class="ui visible error message">
      <div class="header">
        <%= pluralize(resource.errors.count, 'error')%>
      </div>
      <ul>
        <% resource.errors.full_messages.each do |message| %>
            <li><%=	message %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/layouts/_header.html.erb
<header class="ui inverted menu">
  <div class="ui container">
    <%= link_to 'StackOverflow', root_path, {class: 'header item'} %>
    <% if can? :index, User %>
      <%= link_to 'Users', users_path, { class:'item' }%>
    <% end %>
    <div class="right menu">
      <% if !current_user.nil? && (current_user.role == 'admin' && current_user.role == 'moderator') %>
        <div class="item">
          <div class="ui red label">
            <%= current_user.role %>
          </div>
        </div>
      <% end %>
      <% if user_signed_in? %>
          <div class="item">
            <%=  current_user.login %>           
          </div>      
          <div class="item">
            <%= link_to('Profile',  user_path(current_user), class: 'ui primary button') %>
          </div>
          <div class="item">
            <%= link_to('Logout', destroy_user_session_path, method: :delete, class: 'ui  button') %>
          </div>
      <% else %>
          <div class="item">
            <%= link_to('Login', new_user_session_path, class: 'ui primary button')  %>
          </div>
          <div class="item">
            <%= link_to('Sign up', new_user_registration_path, class: 'ui primary button')  %>
          </div>
      <% end %>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shop</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="ui container main-content">
  <% if notice.present? %>
      <div class="ui positive  message  transition ">
        <i class="close icon"></i>
        <%= notice %>
      </div>
  <% end %>
  <% if alert.present? %>
      <div class="ui error  message  transition ">
        <i class="close icon"></i>
        <%= alert %>
      </div>
  <% end %>

  <%= yield %>
</div>
</body>
</html>